apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: starting-react
  annotations:
    github.com/project-slug: Zaperex/starting-react
    pagerduty.com/integration-key: 48ded51e33b34e06c0da3f8291e3c84f
    dynatrace.com/dynatrace-entity-id: fadasdfljhlkasjdf
spec:
  type: other
  lifecycle: unknown
  owner: janus-authors
